{'application': True,
 'author': 'Your Company',
 'category': 'Tools',
 'data': ['security/ir.model.access.csv',
          'data/csv_upload_type_data.xml',
          'views/csv_upload_views.xml',
          'views/glass_report_views.xml',
          'views/frames_cutting_views.xml',
          'views/casing_cutting_views.xml',
          'views/invoice_date_views.xml',
          'views/quotation_to_order_views.xml',
          'views/window_entry_views.xml',
          'views/work_order_views.xml'],
 'depends': ['base', 'sale_management'],
 'installable': True,
 'license': 'LGPL-3',
 'name': 'CSV File Uploader',
 'summary': 'Centralise CSV file imports with audit-ready tracking',
 'version': '18.0.1.0',
 'website': 'https://yourcompany.example.com'}
